# Generated by Django 4.2.23 on 2025-07-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_contactsupportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsupportmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
