# Generated by Django 4.2.23 on 2025-07-18 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_contactsupportmodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.FileField(upload_to='media/')),
                ('file_url', models.CharField(blank=True, max_length=200, null=True)),
                ('file_upload_count', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
