# Generated by Django 4.2.23 on 2025-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_imageanalysismodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysismodel',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
    ]
