# Generated by Django 4.2.23 on 2025-07-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_remove_imageanalysismodel_subscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysismodel',
            name='file_upload_count',
        ),
        migrations.AddField(
            model_name='user',
            name='file_upload_count',
            field=models.IntegerField(default=0),
        ),
    ]
