# Generated by Django 4.2.23 on 2025-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0008_cropimagehistorymodel_orignal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropimagehistorymodel',
            name='COMPOSER',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cropimagehistorymodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
