# Generated by Django 4.2.23 on 2025-07-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_paymentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
