# Generated by Django 4.2.23 on 2025-07-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0011_alter_paymentdetails_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='auth_user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
