# Generated by Django 4.2.23 on 2025-07-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_paymentdetails_auth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='customer_id',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='payment_due',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='payment_status',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='plan_type',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='customer_name',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='date',
            new_name='subscription_id',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='customer_address',
            new_name='thrive_customer_address',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='email',
            new_name='thrive_customer_email',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='thrive_customer_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='thrivecustomer_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
