# Generated by Django 4.2.23 on 2025-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0013_rename_customer_id_paymentdetails_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='mode',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
