# Generated by Django 4.2.23 on 2025-07-31 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0014_paymentdetails_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
    ]
